## Pandas Library in Python

### Definition
Pandas is a powerful, open-source Python library used for data manipulation and analysis. It provides data structures like DataFrames and Series, which are designed to make working with structured data intuitive and efficient.

### Purpose
-   **Data Cleaning and Preparation**: Handles missing data, cleans messy datasets, and reshapes data for analysis.
-   **Data Analysis**: Offers tools for filtering, aggregating, merging, and transforming data, making it suitable for exploratory data analysis (EDA).
-   **Data Storage**: Can read and write data to various formats like CSV, Excel, SQL databases, and HDF5.
-   **Time Series Functionality**: Provides specialized tools for working with time-series data.
-   **Integration**: Seamlessly integrates with other scientific computing libraries in Python, like NumPy and Matplotlib.

### Syntax
To use Pandas, you typically import it with the alias `pd`:

```python
import pandas as pd
```

**Creating Series:**
- From a list: `pd.Series([1, 2, 3])`
- From a dictionary: `pd.Series({'a': 1, 'b': 2})`

**Creating DataFrames:**
- From a dictionary of lists/arrays: `pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})`
- From a list of dictionaries: `pd.DataFrame([{'a': 1, 'b': 2}, {'a': 3, 'b': 4}])`
- Reading from a CSV: `pd.read_csv('file.csv')`

**Common Operations:**
- Accessing columns: `df['column_name']` or `df.column_name`
- Indexing/Slicing: `df.loc[row_label, col_label]`, `df.iloc[row_index, col_index]`
- Filtering: `df[df['column_name'] > value]`
- Grouping: `df.groupby('column_name').agg({'col_to_agg': 'sum'})`
- Missing data: `df.isnull()`, `df.dropna()`, `df.fillna()`

### Simple Python Example

In [ ]:
import pandas as pd
import numpy as np

# 1. Creating a Series
s = pd.Series([10, 20, 30, np.nan, 50], name='MySeries')
print("--- Series Example ---")
print(s)
print(f"Type of s: {type(s)}")

print("\n---")

# 2. Creating a DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [24, 27, 22, 32, np.nan],
    'City': ['New York', 'Paris', 'London', 'New York', 'London'],
    'Salary': [50000, 60000, 45000, 75000, 55000]
}
df = pd.DataFrame(data)
print("--- DataFrame Example ---")
print(df)
print(f"Type of df: {type(df)}")
print(f"DataFrame Info:\n")
df.info()

print("\n---")

# 3. Basic DataFrame Operations
# Select a column
print("--- Select 'Name' column ---")
print(df['Name'])

# Select multiple columns
print("\n--- Select 'Name' and 'Salary' columns ---")
print(df[['Name', 'Salary']])

# Filter rows where Age is greater than 25
print("\n--- Filter: Age > 25 ---")
print(df[df['Age'] > 25])

# Add a new column
df['Bonus'] = df['Salary'] * 0.10
print("\n--- DataFrame with 'Bonus' column ---")
print(df)

# Group by 'City' and calculate average salary
print("\n--- Average Salary by City ---")
print(df.groupby('City')['Salary'].mean())

# Handle missing values: fill NaN in 'Age' with the mean age
mean_age = df['Age'].mean()
df['Age'].fillna(mean_age, inplace=True)
print("\n--- DataFrame after filling missing Age ---")
print(df)


### Explanation of the Code
- **`import pandas as pd` and `import numpy as np`**: Imports the Pandas library with the conventional alias `pd` and NumPy as `np` (often used together, especially for `np.nan` to represent missing data).
- **Creating a Series**: `pd.Series()` creates a one-dimensional labeled array. `np.nan` is used to introduce a missing value.
- **Creating a DataFrame**: `pd.DataFrame(data)` creates a two-dimensional labeled data structure (like a table) from a dictionary where keys are column names and values are lists of data. `df.info()` provides a summary of the DataFrame, including data types and non-null counts.
- **Selecting Columns**: Columns can be selected using bracket notation (`df['Name']`) for a single column (resulting in a Series) or a list of column names (`df[['Name', 'Salary']]`) for multiple columns (resulting in another DataFrame).
- **Filtering Rows**: Boolean indexing `df[df['Age'] > 25]` is used to select rows that satisfy a specific condition.
- **Adding a New Column**: A new column `Bonus` is added by performing an operation on an existing column.
- **Grouping Data**: `df.groupby('City')['Salary'].mean()` groups the DataFrame by the 'City' column and then calculates the mean 'Salary' for each city, demonstrating aggregation.
- **Handling Missing Values**: `df['Age'].fillna(mean_age, inplace=True)` calculates the mean of the 'Age' column and then fills any `np.nan` (missing) values in that column with the calculated mean. `inplace=True` modifies the DataFrame directly.

### Real-world Analogy
Imagine **Pandas** as a highly organized and powerful **filing cabinet with an intelligent assistant**.

- A **DataFrame** is like a **single drawer in that filing cabinet**, where each file folder is a column (e.g., 'Name', 'Age', 'Salary'), and each document inside a folder is a row of data. All the files in a folder contain the same type of information, but each row represents a unique record.
- A **Series** is like a **single file folder** from that drawer, containing only one type of information (e.g., just the 'Name' column).
- **Pandas' functions** are like the intelligent assistant: you can tell it to "find all documents where the 'Age' is over 25" (filtering), "calculate the average 'Salary' for each 'City'" (grouping and aggregation), or "clean up any smudged entries in the 'Age' column by filling them with the average" (handling missing values). This assistant does all the tedious work efficiently, allowing you to focus on the insights rather than manual data manipulation.

## NumPy Library in Python

### Definition
NumPy (Numerical Python) is a fundamental library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays efficiently.

### Purpose
- **Efficient Storage and Operations**: NumPy's core object is the `ndarray` (n-dimensional array), which stores data in a contiguous block of memory, making it much more efficient for numerical operations compared to Python's built-in lists.
- **Vectorization**: It enables computations on entire arrays without explicit loops, leading to significantly faster execution times (often referred to as 'vectorized operations').
- **Foundation for Data Science**: Many other scientific and data analysis libraries in Python (like Pandas, SciPy, Scikit-learn) are built on top of NumPy, leveraging its array object and powerful operations.
- **Mathematical Functions**: Provides a vast collection of mathematical functions (linear algebra, Fourier transforms, random number capabilities, etc.) that can be applied to arrays.

### Syntax
To use NumPy, you typically import it with the alias `np`:

```python
import numpy as np
```

**Creating Arrays:**
- From a Python list: `np.array([1, 2, 3])`
- Array of zeros: `np.zeros((rows, columns))`
- Array of ones: `np.ones((rows, columns))`
- Array with a range of numbers: `np.arange(start, stop, step)`
- Identity matrix: `np.identity(size)`

**Common Operations:**
- Element-wise operations: `array1 + array2`, `array * scalar`
- Dot product: `np.dot(array1, array2)` or `array1 @ array2`
- Reshaping: `array.reshape(new_shape)`
- Accessing elements: `array[row, column]`, `array[start:end]`

### Simple Python Example

In [ ]:
import numpy as np

# 1. Creating a 1D NumPy array from a Python list
list_data = [1, 2, 3, 4, 5]
np_array_1d = np.array(list_data)
print(f"1D Array: {np_array_1d}")
print(f"Type of 1D Array: {type(np_array_1d)}")
print(f"Shape of 1D Array: {np_array_1d.shape}") # (5,) means 5 elements, 1 dimension
print(f"Data type of elements: {np_array_1d.dtype}")

print("\n---")

# 2. Creating a 2D NumPy array (matrix)
matrix_data = [[1, 2, 3], [4, 5, 6]]
np_array_2d = np.array(matrix_data)
print(f"2D Array:\n{np_array_2d}")
print(f"Shape of 2D Array: {np_array_2d.shape}") # (2, 3) means 2 rows, 3 columns
print(f"Number of dimensions: {np_array_2d.ndim}")

print("\n---")

# 3. Basic arithmetic operations (element-wise)
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(f"Array a: {a}")
print(f"Array b: {b}")
print(f"Addition (a + b): {a + b}") # [10+1, 20+2, 30+3]
print(f"Multiplication (a * 2): {a * 2}") # [10*2, 20*2, 30*2]
print(f"Squaring (a**2): {a**2}")

print("\n---")

# 4. Array creation routines
zeros_array = np.zeros((2, 4))
ones_array = np.ones((3, 2))
range_array = np.arange(0, 10, 2) # Start, Stop (exclusive), Step

print(f"Zeros Array (2x4):\n{zeros_array}")
print(f"Ones Array (3x2):\n{ones_array}")
print(f"Range Array: {range_array}")

print("\n---")

# 5. Indexing and Slicing
my_matrix = np.array([[10, 11, 12],
                      [20, 21, 22],
                      [30, 31, 32]])

print(f"Original Matrix:\n{my_matrix}")
print(f"Element at (0, 1): {my_matrix[0, 1]}") # First row, second column (value 11)
print(f"First row: {my_matrix[0, :]}") # Or simply my_matrix[0]
print(f"Second column: {my_matrix[:, 1]}")
print(f"Subset (rows 0-1, cols 1-2):\n{my_matrix[0:2, 1:3]}")

print("\n---")

# 6. Aggregation functions
random_numbers = np.array([5, 1, 8, 2, 7])
print(f"Random Numbers: {random_numbers}")
print(f"Sum of elements: {np.sum(random_numbers)}")
print(f"Mean of elements: {np.mean(random_numbers)}")
print(f"Max element: {np.max(random_numbers)}")

### Explanation of the Code
- **`import numpy as np`**: This is the standard way to import the NumPy library, giving it the alias `np` for convenience.
- **Creating Arrays**: We create 1D and 2D arrays (`np_array_1d`, `np_array_2d`) using `np.array()` from Python lists. The output shows their type as `numpy.ndarray`, along with their `shape` (dimensions) and `dtype` (data type of elements).
- **Basic Arithmetic Operations**: Demonstrates that arithmetic operations (`+`, `*`, `**`) on NumPy arrays are performed element-wise. This means the operation is applied to corresponding elements of arrays or to each element of an array with a scalar.
- **Array Creation Routines**: Shows convenient functions like `np.zeros()` to create an array filled with zeros, `np.ones()` for ones, and `np.arange()` to create an array with evenly spaced values within a given interval.
- **Indexing and Slicing**: Illustrates how to access individual elements (`my_matrix[0, 1]`) and sub-arrays (slices) using NumPy's powerful indexing capabilities, similar to Python lists but extended for multiple dimensions.
- **Aggregation Functions**: Shows how built-in NumPy functions like `np.sum()`, `np.mean()`, and `np.max()` can quickly compute statistics across array elements.

### Real-world Analogy
Imagine you are working with a **spreadsheet application like Excel**.

- A **NumPy array (`ndarray`)** is like a **single sheet** in that spreadsheet. Instead of cells containing just anything, all cells in a NumPy array are designed to hold the same type of numerical data (e.g., all integers, all floats). This homogeneity makes it incredibly efficient for calculations.
- **Vectorized operations** are like applying a formula to an entire column or row instantly without having to drag it down cell by cell. For example, if you want to double every number in a column, with NumPy, you just say `column_array * 2`, and it's done in a blink.
- **Python lists** would be more like individual, unconnected cells, where each cell can hold a completely different type of data, and performing calculations on a whole column would require manually looping through each cell, which is slower.

## 1. Modulus Operator (`%`)

### Definition
The modulus operator (`%`) in Python returns the remainder of the division of one number by another. It's often referred to as the "remainder operator."

### Purpose
To find the remainder after division. This is useful for:
- Determining if a number is even or odd.
- Implementing cyclical behavior (e.g., in clocks or calendars).
- Checking divisibility.
- Generating repeating patterns.

### Syntax
The modulus operator is a binary operator, taking two operands:

```python
result = dividend % divisor
```

### Simple Python Example


In [ ]:
# Example 1: Basic positive numbers
print(f"10 % 3 = {10 % 3}") # 10 divided by 3 is 3 with remainder 1
print(f"12 % 4 = {12 % 4}") # 12 divided by 4 is 3 with remainder 0
print(f"7 % 2 = {7 % 2}")   # Used to check for odd/even

# Example 2: Negative numbers (Python's behavior matches the sign of the divisor)
print(f"-10 % 3 = {-10 % 3}") # -10 = 3 * (-4) + 2 (remainder has same sign as divisor)
print(f"10 % -3 = {10 % -3}") # 10 = (-3) * (-3) + 1 (remainder has same sign as divisor)
print(f"-10 % -3 = {-10 % -3}") # -10 = (-3) * 4 + 2 (remainder has same sign as divisor)

# Example 3: Floating-point numbers
print(f"10.5 % 3 = {10.5 % 3}")
print(f"12.0 % 4.0 = {12.0 % 4.0}")

# Example 4: Cyclical behavior (e.g., clock hours)
current_hour = 17 # 5 PM
hours_to_add = 8
new_hour = (current_hour + hours_to_add) % 12
print(f"If current hour is {current_hour} (5 PM) and we add {hours_to_add} hours, it will be {new_hour} o'clock.")

### Explanation of the Code
- **Basic positive numbers**: Demonstrates the core functionality. `10 % 3` gives `1` because `10 = 3 * 3 + 1`. `12 % 4` gives `0` because `12` is perfectly divisible by `4`. `7 % 2` gives `1`, indicating an odd number.
- **Negative numbers**: Python's modulo behavior ensures the remainder has the same sign as the *divisor*. For `(-10 % 3)`, Python finds the largest multiple of `3` less than or equal to `-10` (which is `-12`), then `-10 - (-12) = 2`. For `(10 % -3)`, the largest multiple of `-3` less than or equal to `10` is `9` (or more accurately, `10 = (-3) * (-3) + 1`), resulting in `1`.
- **Floating-point numbers**: The modulus operator also works with floats, calculating the remainder in a similar fashion.
- **Cyclical behavior**: Shows a practical application. If it's `17` (5 PM) and you add `8` hours, `17 + 8 = 25`. `25 % 12` gives `1`, correctly indicating 1 o'clock (AM).

### Real-world Analogy
Imagine you have a **digital clock that only shows hours from 0 to 11**. If it's `8` o'clock and you want to know what time it will be in `5` hours, you would add `8 + 5 = 13`. Since the clock only goes up to `11`, you wrap around. `13 % 12` gives `1`. So, it will be `1` o'clock. The modulus operator is like the clock face's ability to wrap around when the numbers exceed its maximum.

## 2. Packages

### Definition
A Python package is a way of organizing related modules (single `.py` files) into a directory hierarchy. It's essentially a directory containing a special file named `__init__.py` (which can be empty) and possibly other module files or subdirectories (sub-packages).

### Purpose
- **Modularity and Organization**: Helps structure larger applications by grouping related functionality, making code easier to manage, understand, and maintain.
- **Preventing Name Clashes**: Allows modules with the same name to coexist in different packages (e.g., `package_a.module_x` and `package_b.module_x`).
- **Reusability and Distribution**: Facilitates the reuse of code across different projects and makes it easier to distribute your code as libraries to others.

### Syntax
To create a package, you simply create a directory and place an `__init__.py` file inside it. Other modules (Python files) or subdirectories (sub-packages) can then reside within this package directory.

**Example Directory Structure:**
```
my_project/
├── main.py
└── my_package/
    ├── __init__.py
    ├── module_a.py
    └── sub_package/
        ├── __init__.py
        └── module_b.py
```

**Importing from a package:**
```python
# Option 1: Import the entire module
import my_package.module_a
my_package.module_a.function_from_a()

# Option 2: Import specific items from a module
from my_package.module_a import function_from_a
function_from_a()

# Option 3: Import a sub-package module
from my_package.sub_package import module_b
module_b.function_from_b()
```

### Simple Python Example
First, let's create a dummy package structure for demonstration:


In [ ]:
# Create the directory structure for our package
!mkdir -p my_package/sub_package

# Create __init__.py files
!touch my_package/__init__.py
!touch my_package/sub_package/__init__.py

# Create module_a.py
with open('my_package/module_a.py', 'w') as f:
    f.write("""def greet(name):
    return f"Hello from module_a, {name}!"

def add(a, b):
    return a + b
""")

# Create module_b.py inside sub_package
with open('my_package/sub_package/module_b.py', 'w') as f:
    f.write("""def farewell(name):
    return f"Goodbye from module_b, {name}!"

def multiply(a, b):
    return a * b
""")

print("Package structure created successfully.")

Now we can demonstrate importing and using the created package and its modules:


In [ ]:
# Import the entire module_a
import my_package.module_a
print(my_package.module_a.greet("Alice"))
print(f"Addition result: {my_package.module_a.add(5, 3)}")

print("---")

# Import specific functions from module_a
from my_package.module_a import greet, add
print(greet("Bob"))
print(f"Addition result (direct): {add(10, 2)}")

print("---")

# Import a module from a sub-package
from my_package.sub_package import module_b
print(module_b.farewell("Charlie"))
print(f"Multiplication result: {module_b.multiply(4, 6)}")

print("---")

# You can also import specific functions from a sub-package module
from my_package.sub_package.module_b import multiply
print(f"Multiplication result (direct): {multiply(7, 8)}")

### Explanation of the Code
- We first use shell commands (`!mkdir -p`, `!touch`, and `with open(...)`) to programmatically create a directory structure mimicking a Python package: `my_package` contains `__init__.py` and `module_a.py`, and it also contains a `sub_package` directory which itself has `__init__.py` and `module_b.py`.
- `module_a.py` and `module_b.py` contain simple functions (`greet`, `add`, `farewell`, `multiply`).
- The import statements demonstrate different ways to bring the package's contents into the current scope:
    - `import my_package.module_a`: Imports `module_a` as an object, and you access its functions using `my_package.module_a.function_name()`.
    - `from my_package.module_a import greet, add`: Imports specific functions directly, allowing you to call them without the `my_package.module_a.` prefix.
    - `from my_package.sub_package import module_b`: Imports `module_b` from within `sub_package`, which is nested inside `my_package`. You then access its functions via `module_b.function_name()`.
    - `from my_package.sub_package.module_b import multiply`: Directly imports a function from a module within a sub-package.

### Real-world Analogy
Think of **Packages** like a **library**, and **modules** like individual **books** within that library.

- The `my_package` directory is like a specific **section of the library** (e.g., 'Fiction' or 'Science').
- The `__init__.py` file is like the **section's catalog or index** that tells the library system that this directory is indeed a collection of books (modules).
- `module_a.py` and `module_b.py` are individual **books** containing specific information or tools (functions, classes).
- `sub_package` is like a **sub-section** within the main 'Fiction' section (e.g., 'Fantasy Novels').
- When you `import my_package.module_a`, you are saying, "Go to the 'Fiction' section, find 'Book A', and I'll refer to things in it as 'Fiction.BookA.chapter_1'".
- When you `from my_package.module_a import greet`, you are saying, "Go to the 'Fiction' section, find 'Book A', and I want to use just the 'greet' function directly here, without typing 'Fiction.BookA' each time."

This organization helps you find what you need quickly and prevents confusion if two different sections of the library happen to have books with similar titles.

## 1. Exception Handling

### Definition
Exception handling in Python is a mechanism to deal with runtime errors, known as 'exceptions,' that disrupt the normal flow of a program. It allows you to gracefully manage and recover from unexpected situations without crashing the entire application.

### Purpose
To prevent program crashes due to unexpected errors, provide robust and user-friendly error messages, and ensure that crucial cleanup operations (like closing files) are always performed, even if errors occur.

### Syntax
Python uses `try`, `except`, `else`, and `finally` blocks for exception handling:

-   **`try`**: The code that might raise an exception is placed inside this block.
-   **`except`**: If an exception occurs in the `try` block, the code in the corresponding `except` block is executed. You can specify different `except` blocks for different types of exceptions.
-   **`else`**: The code in this block is executed if no exception occurs in the `try` block.
-   **`finally`**: The code in this block is *always* executed, regardless of whether an exception occurred or not. It's often used for cleanup operations.

```python
try:
    # Code that might raise an exception
    result = 10 / 0
except ZeroDivisionError:
    # Handle ZeroDivisionError
    print("Cannot divide by zero!")
except ValueError as e:
    # Handle other specific errors
    print(f"Value error: {e}")
else:
    # Executed if no exception occurs
    print("Operation successful.")
finally:
    # Always executed
    print("Execution complete.")
```

### Simple Python Example

In [ ]:
def divide_numbers(a, b):
    try:
        result = a / b
    except ZeroDivisionError:
        print("Error: Cannot divide by zero!")
        return None
    except TypeError:
        print("Error: Invalid input types. Please provide numbers.")
        return None
    else:
        print(f"Division successful. Result: {result}")
        return result
    finally:
        print("Division attempt finished.")

print("--- Valid Division ---")
divide_numbers(10, 2)

print("\n--- Division by Zero ---")
divide_numbers(10, 0)

print("\n--- Invalid Type Input ---")
divide_numbers(10, "hello")


def open_and_read_file(filename):
    try:
        with open(filename, 'r') as f:
            content = f.read()
            print(f"File '{filename}' content:\n{content}")
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
    finally:
        print("File operation attempt finished.")

print("\n--- Existing File Reading ---")
# Create a dummy file for testing
with open('my_test_file.txt', 'w') as f:
    f.write('This is a test file content.')
open_and_read_file('my_test_file.txt')

print("\n--- Non-existent File Reading ---")
open_and_read_file('non_existent_file.txt')


### Explanation of the Code
- The `divide_numbers` function demonstrates handling `ZeroDivisionError` and `TypeError`. If a `ZeroDivisionError` occurs (e.g., `10 / 0`), the first `except` block catches it. If a `TypeError` occurs (e.g., `10 / 'hello'`), the second `except` block catches it.
- The `else` block executes only if no exception occurs, confirming successful division.
- The `finally` block always prints "Division attempt finished.", ensuring that this message appears after every attempt, regardless of success or failure.
- The `open_and_read_file` function demonstrates handling `FileNotFoundError` using a `try-except` block. It attempts to open and read a file. If the file doesn't exist, the `FileNotFoundError` is caught, and an informative message is printed.
- A general `except Exception as e:` is included to catch any other unexpected errors during file operations.
- The `with open(...)` statement is a best practice for file handling, as it automatically ensures the file is closed, even if errors occur (similar in spirit to `finally`).

### Real-world Analogy
Think of **Exception Handling** like a car's **dashboard warning lights** and **safety features**. The `try` block is like driving normally. If a problem occurs (an 'exception'), like low oil pressure (`ZeroDivisionError`) or a flat tire (`FileNotFoundError`), a warning light (`except` block) comes on, telling you exactly what's wrong. You don't just stop driving abruptly; instead, you get information, and maybe you can take corrective action (like refilling oil or changing a tire). The `finally` block is like the routine maintenance checks you do, regardless of whether a warning light came on or not – it always happens to keep things in order.

## 2. File Handling

### Definition
File handling in Python refers to the process of reading from or writing to files on a computer's storage. It allows programs to interact with persistent data, enabling them to store information that remains even after the program has finished running.

### Purpose
To persist data beyond the lifespan of a program's execution, allowing for storage, retrieval, and sharing of information. This includes reading configuration settings, logging program activity, processing datasets, or saving user-generated content.

### Syntax
Python provides built-in functions and methods for file handling:

-   **`open(filename, mode)`**: Opens a file and returns a file object. `mode` specifies how the file will be used (`'r'` for read, `'w'` for write (overwrites), `'a'` for append, `'x'` for exclusive creation, `'b'` for binary, `'+'` for read/write).
-   **`file.read()` / `file.readline()` / `file.readlines()`**: Methods to read content from a file.
-   **`file.write(string)` / `file.writelines(list_of_strings)`**: Methods to write content to a file.
-   **`file.close()`**: Closes the file, releasing system resources.
-   **`with open(...) as file:`**: The recommended way to handle files. It ensures that the file is automatically closed, even if errors occur, making it safer and cleaner.

```python
# Writing to a file
with open('example.txt', 'w') as f:
    f.write('Hello, world!\n')
    f.write('This is a new line.')

# Reading from a file
with open('example.txt', 'r') as f:
    content = f.read()
    print(content)
```

### Simple Python Example

In [ ]:
# 1. Writing to a file
file_to_write = 'my_data.txt'
with open(file_to_write, 'w') as f:
    f.write('Line 1: This is the first line.\n')
    f.write('Line 2: This is the second line.\n')
    f.write('Line 3: Numbers: 1, 2, 3.\n')
print(f"Content written to '{file_to_write}'.")

# 2. Appending to a file
file_to_append = 'my_data.txt'
with open(file_to_append, 'a') as f:
    f.write('Line 4: Appended a new line.\n')
print(f"Content appended to '{file_to_append}'.")

# 3. Reading from a file (full content)
file_to_read = 'my_data.txt'
with open(file_to_read, 'r') as f:
    full_content = f.read()
    print(f"\n--- Full content of '{file_to_read}' ---")
    print(full_content)

# 4. Reading line by line
print(f"\n--- Reading '{file_to_read}' line by line ---")
with open(file_to_read, 'r') as f:
    for line_num, line in enumerate(f):
        print(f"Line {line_num + 1}: {line.strip()}") # .strip() removes newline characters

# 5. Using 'r+' mode (read and write)
file_rplus = 'rplus_example.txt'
with open(file_rplus, 'w+') as f:
    f.write('Initial content.\n')
    f.seek(0) # Move cursor to the beginning to read
    content_rplus = f.read()
    print(f"\n--- Content after writing and reading with 'w+' ---")
    print(content_rplus)
    f.write('Added more content.\n') # Writes after the initial content
    f.seek(0)
    final_content_rplus = f.read()
    print(f"\n--- Final content after more writing with 'w+' ---")
    print(final_content_rplus)


### Explanation of the Code
- **Writing (`'w'`)**: The first block opens `my_data.txt` in write mode (`'w'`). If the file doesn't exist, it's created. If it does exist, its content is truncated (emptied) before writing. It then writes three lines to the file.
- **Appending (`'a'`)**: The second block opens `my_data.txt` in append mode (`'a'`). This adds new content to the end of the existing file without overwriting it.
- **Reading (`'r'`)**: The third block opens `my_data.txt` in read mode (`'r'`) and uses `f.read()` to read and print the entire content of the file as a single string.
- **Reading line by line**: The fourth block demonstrates iterating over the file object directly, which reads the file line by line. `line.strip()` is used to remove the newline character (`\n`) that `f.readline()` or iteration usually includes.
- **Read and Write (`'w+'`)**: The last example uses `'w+'` mode, which opens for both writing and reading. After writing 'Initial content.', `f.seek(0)` is crucial to move the file pointer back to the beginning before reading. It then writes 'Added more content.' which gets appended after the 'Initial content.' because the pointer moved to the end after the first write operation. Reading again from the beginning shows the combined content.
- In all examples, `with open(...) as f:` is used, which ensures that the file `f` is automatically closed when the block is exited, even if errors occur.

### Real-world Analogy
Think of **File Handling** like interacting with a **physical notebook or journal**. You can:
- **`'w'` (Write Mode)**: Get a brand new notebook, or take an existing one and erase everything, then start writing fresh entries.
- **`'a'` (Append Mode)**: Open your journal to the last page and add new entries without disturbing previous ones.
- **`'r'` (Read Mode)**: Open your journal and read its contents from beginning to end.
- **`with open(...) as file:`**: This is like making sure you close the journal after you're done, so no pages get lost or damaged, and it's ready for the next time you need it.

## Python Data Types

Python, being a dynamically typed language, automatically infers the data type of a variable based on the value assigned to it. Here's an explanation of common built-in data types:

## 1. Numbers

### Definition
Numbers in Python are used to store numeric values. Python supports integers, floating-point numbers, and complex numbers.

### Purpose
To perform mathematical operations and represent quantitative values. They are fundamental for counting, measurement, and scientific computing.

### Syntax
- **Integers (`int`)**: Whole numbers (positive, negative, or zero) without a decimal point.
- **Floating-point numbers (`float`)**: Numbers with a decimal point, representing real numbers.
- **Complex numbers (`complex`)**: Numbers with a real and an imaginary part (e.g., `a + bj`).

```python
integer_example = 10
float_example = 3.14
complex_example = 2 + 3j
```

### Simple Python Example


In [5]:
# Integer
num_int = 42

# Float
num_float = 3.14159

# Complex
num_complex = 1 + 2j

print(f"Integer: {num_int}, Type: {type(num_int)}")
print(f"Float: {num_float}, Type: {type(num_float)}")
print(f"Complex: {num_complex}, Type: {type(num_complex)}")

# Arithmetic operations
sum_nums = num_int + num_float
product_nums = num_int * num_complex

print(f"Sum of int and float: {sum_nums}, Type: {type(sum_nums)}")
print(f"Product of int and complex: {product_nums}, Type: {type(product_nums)}")

Integer: 42, Type: <class 'int'>
Float: 3.14159, Type: <class 'float'>
Complex: (1+2j), Type: <class 'complex'>
Sum of int and float: 45.14159, Type: <class 'float'>
Product of int and complex: (42+84j), Type: <class 'complex'>


### Explanation of the Code
- `num_int = 42`: Assigns an integer value to `num_int`. `type()` confirms it's an `int`.
- `num_float = 3.14159`: Assigns a floating-point value. `type()` confirms it's a `float`.
- `num_complex = 1 + 2j`: Assigns a complex number. `type()` confirms it's a `complex`.
- Python handles mixed-type arithmetic, promoting the result to the more complex type (e.g., `int` + `float` results in `float`).

### Real-world Analogy
Think of **Numbers** as different forms of currency. `Integers` are like whole dollar bills ($1, $5, $100). `Floats` are like money with cents ($1.99, $25.50). `Complex numbers` are used in specialized fields like electrical engineering, perhaps like cryptocurrency that has both a real-world value and a digital representation.

## 2. Strings

### Definition
A string (`str`) is a sequence of characters, used to represent text.

### Purpose
To store and manipulate textual information, such as names, messages, sentences, and any form of human-readable data.

### Syntax
Strings are enclosed in single quotes (`'...'`), double quotes (`"..."`), or triple quotes (`'''...'''` or `"""..."""`) for multi-line strings.

```python
single_quote_str = 'Hello, Python!'
double_quote_str = "Python is fun."
multiline_str = """This is a
multi-line string.
"""
```

### Simple Python Example


In [6]:
greeting = "Hello, World!"
name = 'Alice'
message = """This is a
message that spans
multiple lines."""

print(f"Greeting: {greeting}, Type: {type(greeting)}")
print(f"Name: {name}, Type: {type(name)}")
print(f"Multi-line message:\n{message}")

# String operations
full_name = name + " Wonderland"
print(f"Concatenated string: {full_name}")
print(f"First character: {greeting[0]}")
print(f"Length of greeting: {len(greeting)}")
print(f"Substring (World): {greeting[7:12]}")

Greeting: Hello, World!, Type: <class 'str'>
Name: Alice, Type: <class 'str'>
Multi-line message:
This is a
message that spans
multiple lines.
Concatenated string: Alice Wonderland
First character: H
Length of greeting: 13
Substring (World): World


### Explanation of the Code
- `greeting = "Hello, World!"` and `name = 'Alice'`: Demonstrate single and double quotes for string creation.
- `message = """..."""`: Shows how to create a multi-line string using triple quotes.
- Strings support various operations:
    - **Concatenation**: `+` joins strings.
    - **Indexing**: `greeting[0]` accesses individual characters (Python uses 0-based indexing).
    - **Slicing**: `greeting[7:12]` extracts a portion of the string.
    - **`len()`**: Returns the number of characters in the string.

### Real-world Analogy
Imagine **Strings** as words, sentences, or paragraphs in a book. Each character is a letter, and you can combine them to form meaningful text, cut out parts of sentences, or count how many words are in a paragraph.

## 3. Booleans

### Definition
Booleans (`bool`) represent truth values: `True` or `False`.

### Purpose
To control program flow using conditional statements, represent logical states, and perform logical operations. They are essential for decision-making in code.

### Syntax
There are only two boolean values: `True` and `False` (note the capitalization).

```python
is_active = True
is_admin = False
```

### Simple Python Example


In [7]:
is_sunny = True
is_raining = False

print(f"Is it sunny? {is_sunny}, Type: {type(is_sunny)}")
print(f"Is it raining? {is_raining}, Type: {type(is_raining)}")

# Conditional logic
if is_sunny and not is_raining:
    print("It's a beautiful day!")
else:
    print("Maybe stay inside.")

# Comparison operators also return booleans
result = (10 > 5)
print(f"10 > 5 is {result}")

Is it sunny? True, Type: <class 'bool'>
Is it raining? False, Type: <class 'bool'>
It's a beautiful day!
10 > 5 is True


### Explanation of the Code
- `is_sunny = True` and `is_raining = False`: Assign boolean values.
- The `if` statement uses boolean logic (`and`, `not`) to evaluate conditions. If `is_sunny` is `True` and `is_raining` is `False`, the first block executes.
- Comparison operators (e.g., `>`, `<`, `==`) also yield boolean results, which can then be used in further logic.

### Real-world Analogy
Think of **Booleans** as a simple light switch: it's either `ON` (`True`) or `OFF` (`False`). There's no in-between state. You use these switches to make decisions: if the light is `ON`, you can read; if `OFF`, you might turn it on.

## 4. Lists

### Definition
A list (`list`) is an ordered, mutable (changeable) collection of items. Items can be of different data types.

### Purpose
To store a collection of related items that can be dynamically modified (added, removed, changed) after creation. Useful for maintaining sequences of data.

### Syntax
Lists are defined by enclosing comma-separated items within square brackets `[]`.

```python
my_list = [1, 'apple', 3.14, True]
```

### Simple Python Example


In [8]:
fruits = ['apple', 'banana', 'cherry']
numbers = [10, 20, 30, 40, 50]

print(f"Fruits list: {fruits}, Type: {type(fruits)}")
print(f"First fruit: {fruits[0]}")

# Lists are mutable (changeable)
fruits[1] = 'orange'
print(f"Modified fruits list: {fruits}")

# Add an item
fruits.append('grape')
print(f"Fruits after append: {fruits}")

# Remove an item
fruits.remove('apple')
print(f"Fruits after remove: {fruits}")

# Slicing
subset_numbers = numbers[1:4]
print(f"Subset of numbers: {subset_numbers}")

Fruits list: ['apple', 'banana', 'cherry'], Type: <class 'list'>
First fruit: apple
Modified fruits list: ['apple', 'orange', 'cherry']
Fruits after append: ['apple', 'orange', 'cherry', 'grape']
Fruits after remove: ['orange', 'cherry', 'grape']
Subset of numbers: [20, 30, 40]


### Explanation of the Code
- `fruits = ['apple', 'banana', 'cherry']`: Creates a list of strings.
- `fruits[0]`: Accesses the first element using its index.
- `fruits[1] = 'orange'`: Modifies an element in the list, demonstrating mutability.
- `fruits.append('grape')`: Adds an item to the end of the list.
- `fruits.remove('apple')`: Removes a specified item from the list.
- `numbers[1:4]`: Creates a new list containing elements from index 1 up to (but not including) index 4.

### Real-world Analogy
Think of a **List** as your shopping list. You can write items down in order, cross them off, add new items, or change an item (e.g., 'milk' to 'almond milk'). The order matters, and you can change it as needed.

## 5. Tuples

### Definition
A tuple (`tuple`) is an ordered, immutable (unchangeable) collection of items. Like lists, items can be of different data types.

### Purpose
To store a collection of related items that should not be modified after creation. Useful for representing fixed collections of data, such as coordinates or database records, and for functions that need to return multiple values.

### Syntax
Tuples are defined by enclosing comma-separated items within parentheses `()`.

```python
my_tuple = (1, 'banana', 3.14)
```

### Simple Python Example


In [9]:
coordinates = (10.0, 20.0)
days_of_week = ('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun')

print(f"Coordinates: {coordinates}, Type: {type(coordinates)}")
print(f"First day: {days_of_week[0]}")

# Attempting to modify a tuple will raise an error
try:
    coordinates[0] = 15.0
except TypeError as e:
    print(f"Error trying to modify tuple: {e}")

# Tuples can be concatenated
new_tuple = days_of_week + ('New Day',)
print(f"Concatenated tuple: {new_tuple}")

# Tuple unpacking
x, y = coordinates
print(f"Unpacked x: {x}, y: {y}")

Coordinates: (10.0, 20.0), Type: <class 'tuple'>
First day: Mon
Error trying to modify tuple: 'tuple' object does not support item assignment
Concatenated tuple: ('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun', 'New Day')
Unpacked x: 10.0, y: 20.0


### Explanation of the Code
- `coordinates = (10.0, 20.0)`: Creates a tuple representing a fixed pair of values.
- `days_of_week[0]`: Accesses elements by index, similar to lists.
- The `try-except` block demonstrates that attempting to reassign an element in a tuple (`coordinates[0] = 15.0`) results in a `TypeError` because tuples are immutable.
- Tuples can be concatenated using `+` to create a new tuple.
- **Tuple unpacking** (`x, y = coordinates`) allows assigning tuple elements to individual variables, which is a common and useful feature.

### Real-world Analogy
Think of a **Tuple** as a fixed address or phone number. Once set, you generally don't change the individual digits of a phone number or components of an address. If you need a new address, you get an entirely new one, rather than changing parts of the old one.

## 6. Sets

### Definition
A set (`set`) is an unordered collection of unique items. Sets are mutable.

### Purpose
To store unique items and perform mathematical set operations like union, intersection, difference, and symmetric difference. Useful for membership testing and eliminating duplicate entries.

### Syntax
Sets are defined by enclosing comma-separated items within curly braces `{}`. An empty set must be created using `set()`, not `{}` (as `{}` creates an empty dictionary).

```python
my_set = {1, 2, 3, 'apple'}
empty_set = set()
```

### Simple Python Example


In [10]:
unique_numbers = {1, 2, 3, 2, 1}
print(f"Set of unique numbers: {unique_numbers}, Type: {type(unique_numbers)}")

names = {'Alice', 'Bob', 'Charlie'}

# Add an item
names.add('David')
print(f"Names after adding David: {names}")

# Adding an existing item has no effect
names.add('Alice')
print(f"Names after adding existing Alice: {names}")

# Remove an item
names.remove('Bob')
print(f"Names after removing Bob: {names}")

# Set operations
set_a = {1, 2, 3, 4}
set_b = {3, 4, 5, 6}

print(f"Union of A and B: {set_a.union(set_b)}")
print(f"Intersection of A and B: {set_a.intersection(set_b)}")
print(f"Difference (A - B): {set_a.difference(set_b)}")

# Membership testing
print(f"Is 3 in set_a? {3 in set_a}")

Set of unique numbers: {1, 2, 3}, Type: <class 'set'>
Names after adding David: {'Alice', 'Bob', 'David', 'Charlie'}
Names after adding existing Alice: {'Alice', 'Bob', 'David', 'Charlie'}
Names after removing Bob: {'Alice', 'David', 'Charlie'}
Union of A and B: {1, 2, 3, 4, 5, 6}
Intersection of A and B: {3, 4}
Difference (A - B): {1, 2}
Is 3 in set_a? True


### Explanation of the Code
- `unique_numbers = {1, 2, 3, 2, 1}`: When created, duplicate values (`1`, `2`) are automatically removed, leaving only unique elements.
- `names.add('David')`: Adds a new element to the set.
- `names.add('Alice')`: Attempting to add an existing element has no effect, maintaining uniqueness.
- `names.remove('Bob')`: Removes a specified element.
- Set operations like `union()`, `intersection()`, and `difference()` are demonstrated, showing how to combine or compare sets based on their unique elements.
- The `in` operator efficiently checks for membership within a set.

### Real-world Analogy
Consider a **Set** as a collection of unique items you own, like your stamp collection (each stamp is unique). You don't keep duplicates. You can add new stamps, remove old ones, or compare your collection with a friend's to see what stamps you both have (intersection) or what you have that they don't (difference).

## 7. Dictionaries

### Definition
A dictionary (`dict`) is an unordered, mutable collection of key-value pairs. Each key must be unique and immutable (e.g., strings, numbers, tuples), and values can be of any data type.

### Purpose
To store data in a way that allows for efficient retrieval, modification, and organization using descriptive keys rather than numerical indices. Ideal for representing structured data, like records or configuration settings.

### Syntax
Dictionaries are defined by enclosing comma-separated `key: value` pairs within curly braces `{}`.

```python
my_dict = {'name': 'Alice', 'age': 30, 'city': 'New York'}
```

### Simple Python Example


In [11]:
person = {
    'name': 'John Doe',
    'age': 30,
    'is_student': False,
    'hobbies': ['reading', 'hiking']
}

print(f"Person dictionary: {person}, Type: {type(person)}")

# Accessing values by key
print(f"Person's name: {person['name']}")
print(f"Person's age: {person.get('age')}") # Using .get() is safer

# Modifying a value
person['age'] = 31
print(f"Updated age: {person['age']}")

# Adding a new key-value pair
person['email'] = 'john.doe@example.com'
print(f"Dictionary after adding email: {person}")

# Removing a key-value pair
del person['is_student']
print(f"Dictionary after deleting 'is_student': {person}")

# Iterating through keys and values
print("\nAll keys:")
for key in person.keys():
    print(key)

print("\nAll values:")
for value in person.values():
    print(value)

print("\nAll items (key-value pairs):")
for key, value in person.items():
    print(f"{key}: {value}")

Person dictionary: {'name': 'John Doe', 'age': 30, 'is_student': False, 'hobbies': ['reading', 'hiking']}, Type: <class 'dict'>
Person's name: John Doe
Person's age: 30
Updated age: 31
Dictionary after adding email: {'name': 'John Doe', 'age': 31, 'is_student': False, 'hobbies': ['reading', 'hiking'], 'email': 'john.doe@example.com'}
Dictionary after deleting 'is_student': {'name': 'John Doe', 'age': 31, 'hobbies': ['reading', 'hiking'], 'email': 'john.doe@example.com'}

All keys:
name
age
hobbies
email

All values:
John Doe
31
['reading', 'hiking']
john.doe@example.com

All items (key-value pairs):
name: John Doe
age: 31
hobbies: ['reading', 'hiking']
email: john.doe@example.com


### Explanation of the Code
- `person = {...}`: Creates a dictionary where keys (`'name'`, `'age'`, etc.) map to values (like `'John Doe'`, `30`). Values can be of different types, including lists.
- `person['name']`: Accesses a value using its key. `person.get('age')` is a safer way to access, returning `None` if the key doesn't exist, instead of raising an error.
- `person['age'] = 31`: Modifies the value associated with an existing key.
- `person['email'] = 'john.doe@example.com'`: Adds a new key-value pair.
- `del person['is_student']`: Removes a key-value pair from the dictionary.
- The code also demonstrates how to iterate through a dictionary's keys, values, or key-value pairs using `keys()`, `values()`, and `items()` methods, respectively.

### Real-world Analogy
Think of a **Dictionary** as a physical dictionary or a phone book. You look up a word (the `key`) to find its definition (the `value`). Each word is unique, and its definition is associated directly with it. You can add new words and their definitions, or update existing ones.

## 1. Class

### Definition
A Class is a blueprint or a template for creating objects. It defines a common set of attributes (data/variables) and methods (functions) that all objects created from this class will have.

### Purpose
To create user-defined data structures that hold their own data (attributes) and behavior (methods). Classes provide a way to organize and structure code, promoting reusability and modularity.

### Syntax
```python
class ClassName:
    # class attributes
    # constructor (__init__ method)
    def __init__(self, attribute1, attribute2):
        self.attribute1 = attribute1
        self.attribute2 = attribute2

    # instance methods
    def method_name(self, parameter):
        # method body
        pass
```

### Simple Python Example


In [ ]:
class Dog:
    # Class attribute
    species = "Canis familiaris"

    # Constructor (initializer) method
    def __init__(self, name, age):
        self.name = name  # Instance attribute
        self.age = age    # Instance attribute

    # Instance method
    def bark(self):
        return f"{self.name} says Woof!"

    # Another instance method
    def get_age(self):
        return f"{self.name} is {self.age} years old."

# Create objects (instances) of the Dog class
dog1 = Dog("Buddy", 5)
dog2 = Dog("Lucy", 2)

# Access attributes
print(f"Dog 1 Name: {dog1.name}")
print(f"Dog 2 Age: {dog2.age}")
print(f"Dog 1 Species: {dog1.species}")

# Call methods
print(dog1.bark())
print(dog2.get_age())

### Explanation of the Code
- `class Dog:` defines a new class named `Dog`.
- `species = "Canis familiaris"` is a **class attribute**, shared by all instances of the `Dog` class.
- `def __init__(self, name, age):` is the **constructor** method. It's automatically called when a new object is created. `self` refers to the instance of the class. `name` and `age` are parameters passed when creating an object. `self.name` and `self.age` are **instance attributes**, unique to each `Dog` object.
- `def bark(self):` and `def get_age(self):` are **instance methods**. They perform actions associated with an object and can access the object's attributes.
- `dog1 = Dog("Buddy", 5)` creates an **object** (an instance) of the `Dog` class named `dog1` with specific `name` and `age`.
- `dog1.name`, `dog2.age`, `dog1.species` are how we access the attributes of an object.
- `dog1.bark()`, `dog2.get_age()` are how we call the methods of an object.

### Real-world Analogy
Think of a **Class** as a **cookie cutter**. It defines the shape and characteristics (attributes like size, flavor, decoration space, and methods like 'bake' or 'decorate') for all cookies. You don't eat the cookie cutter itself, but you use it to make actual cookies.

## 2. Object

### Definition
An Object (or instance) is a concrete realization of a class. It's a specific entity created based on the blueprint provided by a class, possessing its own unique set of attributes and capable of performing actions defined by the class's methods.

### Purpose
To represent real-world entities or abstract concepts within a program. Objects allow you to work with specific data instances that conform to a class's structure and behavior.

### Syntax
Creating an object (instantiation) typically involves calling the class name as if it were a function, passing any required arguments to its `__init__` method.
```python
object_name = ClassName(argument1, argument2, ...)
```

### Simple Python Example


In [ ]:
class Car:
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year
        self.is_running = False

    def start_engine(self):
        if not self.is_running:
            self.is_running = True
            return f"The {self.year} {self.make} {self.model} engine has started."
        else:
            return f"The {self.year} {self.make} {self.model} engine is already running."

    def stop_engine(self):
        if self.is_running:
            self.is_running = False
            return f"The {self.year} {self.make} {self.model} engine has stopped."
        else:
            return f"The {self.year} {self.make} {self.model} engine is already off."

# Creating objects (instances) of the Car class
car1 = Car("Toyota", "Camry", 2020)
car2 = Car("Honda", "Civic", 2022)

# Accessing attributes and calling methods for car1
print(f"Car 1: {car1.make} {car1.model} ({car1.year})")
print(car1.start_engine())
print(f"Is car1 running? {car1.is_running}")

# Accessing attributes and calling methods for car2
print(f"Car 2: {car2.make} {car2.model} ({car2.year})")
print(car2.start_engine())
print(car2.stop_engine())
print(f"Is car2 running? {car2.is_running}")

### Explanation of the Code
- The `Car` class is defined as a blueprint for cars, with attributes like `make`, `model`, `year`, and `is_running`, and methods like `start_engine` and `stop_engine`.
- `car1 = Car("Toyota", "Camry", 2020)` creates an **object** named `car1`. This `car1` is a specific instance of a `Car`, with its own `make` as "Toyota", `model` as "Camry", etc.
- `car2 = Car("Honda", "Civic", 2022)` creates another distinct **object** `car2`, also based on the `Car` blueprint, but with its own unique attributes.
- Each object maintains its own state (e.g., `car1.is_running` is independent of `car2.is_running`).
- We interact with these specific objects by accessing their attributes (`car1.make`) and calling their methods (`car2.start_engine()`).

### Real-world Analogy
If a **Class** is a **cookie cutter**, then an **Object** is an actual **cookie** baked using that cutter. Each cookie is a distinct entity; it might have slightly different icing or sprinkles, but it follows the same basic shape and recipe defined by the cookie cutter. You can have many cookies (objects) from one cookie cutter (class).

## 3. Encapsulation

### Definition
Encapsulation is the bundling of data (attributes) and the methods (functions) that operate on the data into a single unit (a class). It also restricts direct access to some of an object's components, meaning that the internal state of an object is protected and can only be modified or accessed through its public methods.

### Purpose
- **Data Hiding**: Protects an object's internal state from unintended external modification.
- **Modularity**: Allows changes to the internal implementation of a class without affecting the code that uses the class (as long as the public interface remains consistent).
- **Control over Data**: Provides controlled access to attributes, allowing for validation or custom logic when data is set or retrieved.

### Syntax
In Python, encapsulation is primarily achieved through convention and property decorators. There are no strict `public`, `private`, or `protected` keywords like in some other languages.

- **Public attributes/methods**: Directly accessible (`my_object.attribute`, `my_object.method()`).
- **Protected attributes/methods**: By convention, prefixed with a single underscore (`_my_attribute`, `_my_method()`). This signals to other developers that these are internal to the class and should not be accessed directly, but Python doesn't prevent access.
- **Private attributes/methods**: By convention, prefixed with double underscores (`__my_attribute`, `__my_method()`). Python performs name mangling on these, making them harder (but not impossible) to access directly from outside the class, further signaling they are strictly internal.

It's common to use **properties** (using the `@property` decorator) to provide controlled access to attributes.

### Simple Python Example


In [ ]:
class BankAccount:
    def __init__(self, account_holder, initial_balance=0):
        self.account_holder = account_holder # Public attribute
        self.__balance = initial_balance     # Private attribute (name-mangled)

    # Public method to deposit funds
    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount
            print(f"Deposited ${amount}. New balance: ${self.__balance}")
        else:
            print("Deposit amount must be positive.")

    # Public method to withdraw funds
    def withdraw(self, amount):
        if 0 < amount <= self.__balance:
            self.__balance -= amount
            print(f"Withdrew ${amount}. New balance: ${self.__balance}")
        elif amount > self.__balance:
            print(f"Insufficient funds. Current balance: ${self.__balance}")
        else:
            print("Withdrawal amount must be positive.")

    # Using a property to get the balance (controlled access)
    @property
    def balance(self):
        return self.__balance

    # Using a property with a setter for controlled modification (optional)
    # @balance.setter
    # def balance(self, new_balance):
    #     if new_balance >= 0:
    #         self.__balance = new_balance
    #     else:
    #         print("Balance cannot be negative.")

# Create an account
my_account = BankAccount("Alice Wonderland", 100)

# Access public attribute
print(f"Account holder: {my_account.account_holder}")

# Try to access private attribute directly (will cause AttributeError or mangled access)
# print(my_account.__balance) # This would typically raise an AttributeError
print(f"Current balance (via property): ${my_account.balance}")

# Use public methods to modify the balance
my_account.deposit(50)
my_account.withdraw(30)
my_account.withdraw(200) # Attempt to overdraw
my_account.deposit(-10) # Attempt invalid deposit

print(f"Final balance: ${my_account.balance}")

# Demonstrating name mangling (not recommended for direct use)
# print(my_account._BankAccount__balance)

### Explanation of the Code
- The `BankAccount` class bundles the `account_holder` and `__balance` (data) along with `deposit()`, `withdraw()`, and `balance` (methods/properties) into one unit.
- `self.__balance` is a **private attribute** due to the double underscore prefix. This means it's not meant to be accessed or modified directly from outside the class.
- The `deposit()` and `withdraw()` methods provide **controlled access** to `__balance`. They contain logic to validate transactions (e.g., ensure deposit amount is positive, prevent overdrafts).
- The `@property` decorator on the `balance` method turns it into a **getter**. This allows us to retrieve the `__balance` value using `my_account.balance` as if it were an attribute, but internally, a method call is executed, providing a controlled way to read the data without direct access.
- If you uncomment the `@balance.setter` block, you could also provide controlled writing to the `__balance` attribute.
- Attempting to access `my_account.__balance` directly will fail, reinforcing the encapsulation.

### Real-world Analogy
Think of a **TV remote control** as the public interface to your TV. You use buttons (methods like `volume_up`, `channel_change`, `power_on`) to interact with the TV. You don't directly manipulate the TV's internal circuitry (private attributes like the circuit board, wires, or resistors). The TV's internal workings are **encapsulated**; you only interact with them through the defined interface (the remote's buttons/methods). This protects the TV from accidental damage and makes it easier to use without needing to understand its complex internal design.

## 4. Inheritance

### Definition
Inheritance is a mechanism that allows a new class (subclass/derived class) to acquire attributes and methods from an existing class (superclass/base class). This promotes code reusability and establishes a natural "is-a" relationship between classes.

### Purpose
- **Code Reusability**: Common functionality can be defined in a base class and reused in multiple derived classes.
- **Extension**: Subclasses can extend or specialize the behavior of the base class by adding new attributes, new methods, or overriding existing ones.
- **Hierarchy**: It helps create a hierarchical structure for classes, modeling real-world relationships.

### Syntax
To create a subclass, you specify the base class name in parentheses after the subclass name.
```python
class BaseClass:
    # attributes and methods
    pass

class DerivedClass(BaseClass):
    # additional attributes and methods specific to DerivedClass
    # can also override methods from BaseClass
    pass
```
`super()` is often used to call methods or the constructor of the parent class.

### Simple Python Example


In [ ]:
class Animal:
    def __init__(self, name, species):
        self.name = name
        self.species = species

    def speak(self):
        return f"{self.name} makes a sound."

    def describe(self):
        return f"{self.name} is a {self.species}."

class Dog(Animal):
    def __init__(self, name, breed):
        # Call the constructor of the parent class (Animal)
        super().__init__(name, species="Dog")
        self.breed = breed

    # Override the speak method specific to Dog
    def speak(self):
        return f"{self.name} barks!"

    # Add a new method specific to Dog
    def fetch(self, item):
        return f"{self.name} fetches the {item}."

class Cat(Animal):
    def __init__(self, name, color):
        super().__init__(name, species="Cat")
        self.color = color

    # Override the speak method specific to Cat
    def speak(self):
        return f"{self.name} meows!"

    # Add a new method specific to Cat
    def climb(self):
        return f"{self.name} climbs a tree."

# Create objects
animal = Animal("Generic", "Unknown")
dog = Dog("Buddy", "Golden Retriever")
cat = Cat("Whiskers", "Tabby")

# Demonstrate Animal class functionality
print(animal.describe())
print(animal.speak())
print("---")

# Demonstrate Dog class functionality (inherits from Animal, overrides speak, adds fetch)
print(dog.describe()) # Inherited from Animal
print(dog.speak())    # Overridden in Dog
print(dog.fetch("ball")) # New method in Dog
print(f"Buddy's breed: {dog.breed}")
print("---")

# Demonstrate Cat class functionality (inherits from Animal, overrides speak, adds climb)
print(cat.describe()) # Inherited from Animal
print(cat.speak())    # Overridden in Cat
print(cat.climb())    # New method in Cat
print(f"Whiskers' color: {cat.color}")

### Explanation of the Code
- `Animal` is the **base class** with common attributes (`name`, `species`) and methods (`speak`, `describe`).
- `Dog(Animal)` defines `Dog` as a **subclass** that inherits from `Animal`. This signifies an "is-a" relationship (a Dog *is an* Animal).
- In `Dog`'s `__init__`, `super().__init__(name, species="Dog")` calls the constructor of the `Animal` class to initialize the inherited `name` and `species` attributes.
- The `speak()` method is **overridden** in both `Dog` and `Cat` classes to provide species-specific sounds, demonstrating polymorphism.
- `fetch()` is a new method added to the `Dog` class, extending its functionality.
- `Cat(Animal)` similarly defines `Cat` as another subclass, demonstrating how multiple classes can inherit from the same base class and specialize.
- Objects of `Dog` and `Cat` can use methods defined in `Animal` (`describe()`) and also their own specialized methods (`fetch()`, `climb()`) and overridden methods (`speak()`).

### Real-world Analogy
Consider a **"Vehicle"** as a **base class**. It might have general attributes like `speed`, `color`, and methods like `start_engine()`, `drive()`. Now, **"Car"** and **"Motorcycle"** can be **subclasses** that inherit from `Vehicle`. They automatically get the `speed`, `color`, `start_engine()`, and `drive()` functionality. However, a `Car` might add a `number_of_doors` attribute and a `open_trunk()` method, while a `Motorcycle` might add a `handlebar_type` attribute and a `lean()` method. They both are vehicles, but they have their own specialized characteristics and behaviors.

## 5. Polymorphism

### Definition
Polymorphism means "many forms." In OOP, it refers to the ability of different objects to respond to the same method call in their own unique ways. This often happens through method overriding in inherited classes, where a subclass provides its own implementation of a method that is already defined in its superclass.

### Purpose
- **Flexibility and Extensibility**: Allows you to write generic code that can work with objects of different classes, as long as those classes share a common interface (i.e., have methods with the same names).
- **Simplifies Code**: Reduces the need for `if-elif-else` statements or `switch` cases to determine an object's type and call the appropriate method.
- **Dynamic Dispatch**: The appropriate method implementation is chosen at runtime based on the object's actual type.

### Syntax
Polymorphism is not about specific syntax but about how methods are defined and called across a class hierarchy. The key is that subclasses implement methods with the same name as methods in their parent class (method overriding).

### Simple Python Example


In [ ]:
class Animal:
    def speak(self):
        raise NotImplementedError("Subclass must implement abstract method")

class Dog(Animal):
    def speak(self):
        return "Woof!"

class Cat(Animal):
    def speak(self):
        return "Meow!"

class Duck(Animal):
    def speak(self):
        return "Quack!"

# A function that takes an Animal object and calls its speak method
def make_animal_speak(animal_obj):
    print(animal_obj.speak())

# Create different animal objects
dog_obj = Dog()
cat_obj = Cat()
duck_obj = Duck()

# Call the same function with different types of animal objects
make_animal_speak(dog_obj)
make_animal_speak(cat_obj)
make_animal_speak(duck_obj)

print("---")

# Another example: A list of diverse animals
animals = [Dog(), Cat(), Duck()]

for animal in animals:
    make_animal_speak(animal)

print("---")

# Example with a different method where polymorphism also applies
class Shape:
    def area(self):
        raise NotImplementedError("Subclass must implement abstract method")

class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius
    def area(self):
        return 3.14 * self.radius * self.radius

class Rectangle(Shape):
    def __init__(self, width, height):
        self.width = width
        self.height = height
    def area(self):
        return self.width * self.height

shapes = [Circle(5), Rectangle(4, 6)]

for shape in shapes:
    print(f"Area: {shape.area()}")

### Explanation of the Code
- The `Animal` base class defines a `speak()` method (which raises `NotImplementedError` to indicate it should be overridden). This establishes a common interface.
- `Dog`, `Cat`, and `Duck` are subclasses, and each provides its own unique implementation of the `speak()` method.
- The `make_animal_speak()` function takes an `animal_obj`. It doesn't care *what specific type* of `Animal` it is, only that it has a `speak()` method. When `make_animal_speak(dog_obj)` is called, Python automatically calls `Dog`'s `speak()`. When `make_animal_speak(cat_obj)` is called, Python calls `Cat`'s `speak()`, and so on.
- The loop `for animal in animals:` further illustrates this: the same `make_animal_speak()` call behaves differently depending on the actual object type at runtime.
- The `Shape`, `Circle`, and `Rectangle` example shows polymorphism with an `area()` method, where each shape calculates its area differently but is accessed through the same method name.

### Real-world Analogy
Imagine you have a **"Play" button** on different media devices: a CD player, a DVD player, and an MP3 player. When you press the "Play" button on a CD player, it plays a CD. When you press it on a DVD player, it plays a DVD. When you press it on an MP3 player, it plays an MP3 file. The **"Play" action (method name) is the same**, but the **underlying mechanism (implementation) is different** for each device based on what it is designed to play. This is polymorphism – one interface, many implementations.